### ISSUE TITLE
RELEASE file missing from 0.0.13 tarball on pypi

### ISSUE THREAD

**Issue by dpryan79** [Dangertrip/LiBis#3]
FYI, the `RELEASE` file is missing from the 0.0.13 tarball on pypi and this makes installation impossible:

```
06:12:17 BIOCONDA INFO (OUT) Processing $SRC_DIR
06:12:17 BIOCONDA INFO (OUT)   Created temporary directory: /tmp/pip-req-build-x6dksqn2
06:12:17 BIOCONDA INFO (OUT)   Added file://$SRC_DIR to build tracker '/tmp/pip-req-tracker-vnydtp64'
06:12:17 BIOCONDA INFO (OUT)     Running command python setup.py egg_info
06:12:17 BIOCONDA INFO (OUT)     Running setup.py (path:/tmp/pip-req-build-x6dksqn2/setup.py) egg_info for package from file://$SRC_DIR
06:12:17 BIOCONDA INFO (OUT)     Traceback (most recent call last):
06:12:17 BIOCONDA INFO (OUT)       File "<string>", line 1, in <module>
06:12:17 BIOCONDA INFO (OUT)       File "/tmp/pip-req-build-x6dksqn2/setup.py", line 23, in <module>
06:12:17 BIOCONDA INFO (OUT)         with open('RELEASE') as f:
06:12:17 BIOCONDA INFO (OUT)     FileNotFoundError: [Errno 2] No such file or directory: 'RELEASE'
```

**Comment by Dangertrip** [comment]
Thanks! Added RELEASE in tarball on pypi
