### ISSUE TITLE
UnboundLocalError: local variable 'c' referenced before assignment

### ISSUE THREAD

**Issue by rmvpaeme** [Dangertrip/LiBis#4]
I have this error when running LiBis with:

```
LiBis -n CFD1601224-NBL_R1.fastq.gz -r GRCh37.fa  -g GRCh37 --plot --fullmode -qc
```

```
Traceback (most recent call last):
  File "/apps/gent/CO7/haswell-ib/software/LiBis/20200428-foss-2019b-Python-3.7.4/bin/LiBis", line 215, in <module>
    main()
  File "/apps/gent/CO7/haswell-ib/software/LiBis/20200428-foss-2019b-Python-3.7.4/bin/LiBis", line 212, in main
    computeProcess(input_args())
  File "/apps/gent/CO7/haswell-ib/software/LiBis/20200428-foss-2019b-Python-3.7.4/lib/python3.7/site-packages/LiBis/computeProcess.py", line 136, in computeProcess
    name,bsmapresult = computeBsmap(name,bsmap,param) 
  File "/apps/gent/CO7/haswell-ib/software/LiBis/20200428-foss-2019b-Python-3.7.4/lib/python3.7/site-packages/LiBis/computeProcess.py", line 76, in computeBsmap
    newname,logname = bsmap.clipping(n,param,given_bam,given_label)
  File "/apps/gent/CO7/haswell-ib/software/LiBis/20200428-foss-2019b-Python-3.7.4/lib/python3.7/site-packages/LiBis/moabs.py", line 134, in clipping
    newname,log = clipmode(filenames,param, given_bam_file,given_label)
  File "/apps/gent/CO7/haswell-ib/software/LiBis/20200428-foss-2019b-Python-3.7.4/lib/python3.7/site-packages/LiBis/clipmode.py", line 400, in clipmode
    newn,originallog,splitlog,cleanname=clip_process(name,param, given_bam_file,given_label)
  File "/apps/gent/CO7/haswell-ib/software/LiBis/20200428-foss-2019b-Python-3.7.4/lib/python3.7/site-packages/LiBis/clipmode.py", line 311, in clip_process
    reads_num_dist,reads_len_dist = unsortedCombine(unmapped_file[:unmapped_file.find('fastq')-1],args)
  File "/apps/gent/CO7/haswell-ib/software/LiBis/20200428-foss-2019b-Python-3.7.4/lib/python3.7/site-packages/LiBis/mapreduce.py", line 515, in unsortedCombine
    pure_name = c[0]
UnboundLocalError: local variable 'c' referenced before assignment
```

Log files:

```
[ 2020-08-03 16:21:05.905030 ]	Running quality control for samples...
[ 2020-08-03 16:22:38.799056 ]	Finish quality control for samples
[ 2020-08-03 16:22:38.875621 ]	Running Alignment for samples...
[ 2020-08-03 16:22:38.897955 ]	Temprary files cleaning...
[ 2020-08-03 16:22:38.897989 ]	Begin the alignment process with clipping.
[ 2020-08-03 16:22:38.898028 ]	Begin the 1st round full reads mapping.
[ 2020-08-03 17:05:27.474592 ]	Filtering and clipping unmapped reads.
Temporary file doesn't exist: CFD1601224-NBL_R1.unmapped.fastq !
[ 2020-08-03 17:08:21.553470 ]	Begin the 2st round mapping for clipped fragments.
[ 2020-08-03 17:57:55.572260 ]	Recombining uniquely mapped fragments...
```

```
2020-08-03 16:22:38.798689	command: fastqc -o ./Fastqc CFD1601224-NBL_R1.fastq.gz 
Output:
Started analysis of CFD1601224-NBL_R1.fastq.gz
Approx 5% complete for CFD1601224-NBL_R1.fastq.gz
Approx 10% complete for CFD1601224-NBL_R1.fastq.gz
Approx 15% complete for CFD1601224-NBL_R1.fastq.gz
Approx 20% complete for CFD1601224-NBL_R1.fastq.gz
Approx 25% complete for CFD1601224-NBL_R1.fastq.gz
Approx 30% complete for CFD1601224-NBL_R1.fastq.gz
Approx 35% complete for CFD1601224-NBL_R1.fastq.gz
Approx 40% complete for CFD1601224-NBL_R1.fastq.gz
Approx 45% complete for CFD1601224-NBL_R1.fastq.gz
Approx 50% complete for CFD1601224-NBL_R1.fastq.gz
Approx 55% complete for CFD1601224-NBL_R1.fastq.gz
Approx 60% complete for CFD1601224-NBL_R1.fastq.gz
Approx 65% complete for CFD1601224-NBL_R1.fastq.gz
Approx 70% complete for CFD1601224-NBL_R1.fastq.gz
Approx 75% complete for CFD1601224-NBL_R1.fastq.gz
Approx 80% complete for CFD1601224-NBL_R1.fastq.gz
Approx 85% complete for CFD1601224-NBL_R1.fastq.gz
Approx 90% complete for CFD1601224-NBL_R1.fastq.gz
Approx 95% complete for CFD1601224-NBL_R1.fastq.gz


2020-08-03 17:05:27.472918	command: bsmap -a CFD1601224-NBL_R1.fastq.gz -z 33 -d /data/gent/vo/000/gvo00027/RNA_seq_pipeline/resources_Ruben/GRCh37-lite.fa  -o CFD1601224-NBL_R1.bam -S 123 -n 1 -r 0 -U -u -p 8 1>>LiBis_log 2>>BAM_FILE/CFD1601224-NBL_R1_originallog.record
Output:


2020-08-03 17:57:55.570410	command: bsmap -a CFD1601224-NBL_R1.unmapped.fastq -d /data/gent/vo/000/gvo00027/RNA_seq_pipeline/resources_Ruben/GRCh37-lite.fa  -o CFD1601224-NBL_R1.unmapped.bam -n 1 -r 0 -U -R -p 8 1>>LiBis_log 2>>BAM_FILE/CFD1601224-NBL_R1.unmapped_log.txt
Output:
```

**Comment by rmvpaeme** [comment]
The error was fixed after changing line 515 in https://github.com/Dangertrip/LiBis/blob/master/LiBis/mapreduce.py
to
“pure_name = line.query_name”
from
“pure_name = c[0]”

I made a pullrequest #5

**Comment by Dangertrip** [comment]
Thank you for the pull request! Please let me know if you need more information.
